<a href="https://colab.research.google.com/github/Luvi64bit/WebScrapper/blob/main/WebScraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import requests
from bs4 import BeautifulSoup as bs
import re
import pandas as pd

In [11]:
url = 'https://www.carandbike.com/research/top-10-best-cars-in-the-world'

In [3]:
r = requests.get(url)

In [17]:
print(r)

<Response [200]>

In [19]:
soup = bs(r.content)

In [72]:
s = soup.find('table')
s

<table>
<tbody>
<tr>
<td>
<p>Name of the car</p>
</td>
<td>
<p>Top Speed</p>
</td>
<td>
<p>0-100 km/h</p>
</td>
<td>
<p>Torque</p>
</td>
<td>
<p>Power</p>
</td>
</tr>
<tr>
<td>
<p>Lamborghini Sian Roadster</p>
</td>
<td>
<p>&gt;350 kmh/217.48 mp h</p>
</td>
<td>
<p>&lt;2.9 seconds</p>
</td>
<td>
<p>720 NM</p>
</td>
<td>
<p>774 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Pagani Huayra BC Roadster</p>
</td>
<td>
<p>383 kmh/237.98 mph</p>
</td>
<td>
<p>3.3 seconds</p>
</td>
<td>
<p>1049 NM</p>
</td>
<td>
<p>745 bhp</p>
</td>
</tr>
<tr>
<td>
<p>McLaren Speedtail</p>
</td>
<td>
<p>403 kmh/250 mph</p>
</td>
<td>
<p>3 seconds</p>
</td>
<td>
<p>1150 NM</p>
</td>
<td>
<p>1036 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Aston Martin Valkyrie</p>
</td>
<td>
<p>402 kmh/250 mph</p>
</td>
<td>
<p>2.6 seconds</p>
</td>
<td>
<p>900 NM</p>
</td>
<td>
<p>1160 bhpÂ </p>
</td>
</tr>
<tr>
<td>
<p>Hennessey Venom GT</p>
</td>
<td>
<p>435.31 kmh/270.8 mph</p>
</td>
<td>
<p>2.4 seconds</p>
</td>
<td>
<p>1566 NM</p>
</td>
<td>
<p>1244 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Koenigsegg Jesko Absolut</p>
</td>
<td>
<p>483 kmh/300 mph</p>
</td>
<td>
<p>1.9 seconds</p>
</td>
<td>
<p>1500 NM</p>
</td>
<td>
<p>1280 bhp</p>
</td>
</tr>
<tr>
<td>
<p>SSC Tuatara</p>
</td>
<td>
<p>508.73 kmh/316.11 mph</p>
</td>
<td>
<p>2.5 seconds</p>
</td>
<td>
<p>1735 NM</p>
</td>
<td>
<p>1750 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Bugatti Chiron Super Sport 300+</p>
</td>
<td>
<p>482.80 kmh/300 mph</p>
</td>
<td>
<p>2.4 seconds</p>
</td>
<td>
<p>1600 NM</p>
</td>
<td>
<p>1577 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Bugatti Bolide</p>
</td>
<td>
<p>498.89 kmh/310 mph</p>
</td>
<td>
<p>2.17 seconds</p>
</td>
<td>
<p>1850 NM</p>
</td>
<td>
<p>1824 bhp</p>
</td>
</tr>
<tr>
<td>
<p>Koenigsegg CCR</p>
</td>
<td>
<p>388 kmh/241 mph</p>
</td>
<td>
<p>3.7 seconds</p>
</td>
<td>
<p>920 NM</p>
</td>
<td>
<p>806 bhp</p>
</td>
</tr>
</tbody>
</table>

In [75]:
content = s.find_all('td')
content

[<td>
 <p>Name of the car</p>
 </td>,
 <td>
 <p>Top Speed</p>
 </td>,
 <td>
 <p>0-100 km/h</p>
 </td>,
 <td>
 <p>Torque</p>
 </td>,
 <td>
 <p>Power</p>
 </td>,
 <td>
 <p>Lamborghini Sian Roadster</p>
 </td>,
 <td>
 <p>&gt;350 kmh/217.48 mp h</p>
 </td>,
 <td>
 <p>&lt;2.9 seconds</p>
 </td>,
 <td>
 <p>720 NM</p>
 </td>,
 <td>
 <p>774 bhp</p>
 </td>,
 <td>
 <p>Pagani Huayra BC Roadster</p>
 </td>,
 <td>
 <p>383 kmh/237.98 mph</p>
 </td>,
 <td>
 <p>3.3 seconds</p>
 </td>,
 <td>
 <p>1049 NM</p>
 </td>,
 <td>
 <p>745 bhp</p>
 </td>,
 <td>
 <p>McLaren Speedtail</p>
 </td>,
 <td>
 <p>403 kmh/250 mph</p>
 </td>,
 <td>
 <p>3 seconds</p>
 </td>,
 <td>
 <p>1150 NM</p>
 </td>,
 <td>
 <p>1036 bhp</p>
 </td>,
 <td>
 <p>Aston Martin Valkyrie</p>
 </td>,
 <td>
 <p>402 kmh/250 mph</p>
 </td>,
 <td>
 <p>2.6 seconds</p>
 </td>,
 <td>
 <p>900 NM</p>
 </td>,
 <td>
 <p>1160 bhpÂ </p>
 </td>,
 <td>
 <p>Hennessey Venom GT</p>
 </td>,
 <td>
 <p>435.31 kmh/270.8 mph</p>
 </td>,
 <td>
 <p>2.4 seconds</p>
 </td>,
 <td>
 <p>1566 NM</p>
 </td>,
 <td>
 <p>1244 bhp</p>
 </td>,
 <td>
 <p>Koenigsegg Jesko Absolut</p>
 </td>,
 <td>
 <p>483 kmh/300 mph</p>
 </td>,
 <td>
 <p>1.9 seconds</p>
 </td>,
 <td>
 <p>1500 NM</p>
 </td>,
 <td>
 <p>1280 bhp</p>
 </td>,
 <td>
 <p>SSC Tuatara</p>
 </td>,
 <td>
 <p>508.73 kmh/316.11 mph</p>
 </td>,
 <td>
 <p>2.5 seconds</p>
 </td>,
 <td>
 <p>1735 NM</p>
 </td>,
 <td>
 <p>1750 bhp</p>
 </td>,
 <td>
 <p>Bugatti Chiron Super Sport 300+</p>
 </td>,
 <td>
 <p>482.80 kmh/300 mph</p>
 </td>,
 <td>
 <p>2.4 seconds</p>
 </td>,
 <td>
 <p>1600 NM</p>
 </td>,
 <td>
 <p>1577 bhp</p>
 </td>,
 <td>
 <p>Bugatti Bolide</p>
 </td>,
 <td>
 <p>498.89 kmh/310 mph</p>
 </td>,
 <td>
 <p>2.17 seconds</p>
 </td>,
 <td>
 <p>1850 NM</p>
 </td>,
 <td>
 <p>1824 bhp</p>
 </td>,
 <td>
 <p>Koenigsegg CCR</p>
 </td>,
 <td>
 <p>388 kmh/241 mph</p>
 </td>,
 <td>
 <p>3.7 seconds</p>
 </td>,
 <td>
 <p>920 NM</p>
 </td>,
 <td>
 <p>806 bhp</p>
 </td>]

In [91]:
content[0]
pattern = '\n|<td>|<p>|</p>|</td>|&gt;|&lt;'
re.sub(pattern,'',str(content[7]))

'2.9 seconds'

In [100]:
Name_of_the_Car = []
Top_Speed = []
zero_100_km_per_h = []
Torque = []
Power =  []

In [101]:
count = 0
for i in content:
  pattern = '\n|<td>|<p>|</p>|</td>|&gt;|&lt;'
  value = re.sub(pattern,'',str(i))

  if count == 0:
    Name_of_the_Car.append(value)
    count +=1
  elif count == 1:
    Top_Speed.append(value)
    count +=1
  elif count == 2:
    zero_100_km_per_h.append(value)
    count +=1
  elif count == 3:
    Torque.append(value)
    count +=1
  else :
    Power.append(value)
    count = 0

In [104]:
Name_of_the_Car = Name_of_the_Car[1:]
Top_Speed = Top_Speed[1:]
zero_100_km_per_h = zero_100_km_per_h[1:]
Torque = Torque[1:]
Power =  Power[1:]

In [109]:
len(Power)

10

In [110]:
# Create a dictionary containing the data
data = {'Name': Name_of_the_Car[0:10],
        'Top_Speed': Top_Speed[0:10],
        '0-100_km_per_h': zero_100_km_per_h[0:10],
        'Torque':Torque[0:10],
        'Power':Power[0:10]}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

In [111]:
df

,Name,Top_Speed,0-100_km_per_h,Torque,Power
0,Lamborghini Sian Roadster,350 kmh/217.48 mp h,2.9 seconds,720 NM,774 bhp
1,Pagani Huayra BC Roadster,383 kmh/237.98 mph,3.3 seconds,1049 NM,745 bhp
2,McLaren Speedtail,403 kmh/250 mph,3 seconds,1150 NM,1036 bhp
3,Aston Martin Valkyrie,402 kmh/250 mph,2.6 seconds,900 NM,1160 bhp
4,Hennessey Venom GT,435.31 kmh/270.8 mph,2.4 seconds,1566 NM,1244 bhp
5,Koenigsegg Jesko Absolut,483 kmh/300 mph,1.9 seconds,1500 NM,1280 bhp
6,SSC Tuatara,508.73 kmh/316.11 mph,2.5 seconds,1735 NM,1750 bhp
7,Bugatti Chiron Super Sport 300+,482.80 kmh/300 mph,2.4 seconds,1600 NM,1577 bhp
8,Bugatti Bolide,498.89 kmh/310 mph,2.17 seconds,1850 NM,1824 bhp
9,Koenigsegg CCR,388 kmh/241 mph,3.7 seconds,920 NM,806 bhp